language: c

before_install:
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then sudo gem install xcpretty-travis-formatter; fi

sudo: required
dist: trusty
env:
    global:
        - OPENRCT2_VERSION="0.0.5.0"

matrix:
    include:
        - os: linux
          env:
          after_success:
            - curl -o - -v "https://openrct2.org/"

script:
    - true

notifications:
    on_failure: change
    on_success: change
